WITH ItemSpine AS (
    SELECT ITEMNMBR FROM dbo.ETB_PAB_MO
    UNION
    SELECT ITEMNMBR FROM dbo.Prosenthal_Vendor_Items
    UNION
    SELECT ITEMNMBR FROM dbo.ETB_ActiveDemand_Union_FG_MO
),
CleanData AS (
    SELECT
        LTRIM(RTRIM(mo.ITEMNMBR)) AS ITEMNMBR,
        LTRIM(RTRIM(mo.ITEMDESC)) AS ItemDescription,
        LTRIM(RTRIM(mo.UOFM)) AS UOM,
        LTRIM(RTRIM(mo.ORDERNUMBER)) AS ORDERNUMBER,
        LTRIM(RTRIM(mo.Construct)) AS Construct,
        mo.DUEDATE,
        mo.[Expiry Dates],
        mo.[Date + Expiry],
        TRY_CAST(NULLIF(LTRIM(RTRIM(mo.BEG_BAL)), '') AS decimal(18,6)) AS BEG_BAL,
        mo.Deductions,
        mo.Expiry,
        mo.[PO's],
        mo.Running_Balance,
        mo.MRP_IssueDate,
        mo.WCID_From_MO,
        mo.Issued,
        mo.Remaining AS Original_Required,
        mo.Has_Issued,
        mo.IssueDate_Mismatch,
        mo.Early_Issue_Flag,
        REPLACE(LTRIM(RTRIM(mo.ORDERNUMBER)), '-', '') AS CleanOrder,
        REPLACE(LTRIM(RTRIM(mo.ITEMNMBR)), '-', '') AS CleanItem
    FROM dbo.ETB_PAB_MO mo
),
ActiveDemandJoin AS (
    SELECT
        cd.ITEMNMBR,
        cd.ItemDescription,
        cd.UOM,
        cd.ORDERNUMBER,
        cd.Construct,
        cd.DUEDATE,
        cd.[Expiry Dates],
        cd.[Date + Expiry],
        cd.BEG_BAL,
        cd.Deductions,
        cd.Expiry,
        cd.[PO's],
        cd.Running_Balance,
        cd.MRP_IssueDate,
        cd.WCID_From_MO,
        cd.Issued,
        cd.Original_Required,
        cd.Has_Issued,
        cd.IssueDate_Mismatch,
        cd.Early_Issue_Flag,
        cd.CleanOrder,
        cd.CleanItem,
        ad.FG,
        ad.[FG Desc],
        ad.STSDESCR,
        ad.MRPTYPE
    FROM CleanData cd
    LEFT JOIN dbo.ETB_ActiveDemand_Union_FG_MO ad
        ON cd.CleanOrder = REPLACE(LTRIM(RTRIM(ad.ORDERNUMBER)), '-', '')
        AND cd.CleanItem = REPLACE(LTRIM(RTRIM(ad.ITEMNMBR)), '-', '')
),
VendorItemJoin AS (
    SELECT
        adj.ITEMNMBR,
        adj.ItemDescription,
        adj.UOM,
        adj.ORDERNUMBER,
        adj.Construct,
        adj.DUEDATE,
        adj.[Expiry Dates],
        adj.[Date + Expiry],
        adj.BEG_BAL,
        adj.Deductions,
        adj.Expiry,
        adj.[PO's],
        adj.Running_Balance,
        adj.MRP_IssueDate,
        adj.WCID_From_MO,
        adj.Issued,
        adj.Original_Required,
        adj.Has_Issued,
        adj.IssueDate_Mismatch,
        adj.Early_Issue_Flag,
        adj.CleanOrder,
        adj.CleanItem,
        adj.FG,
        adj.[FG Desc],
        adj.STSDESCR,
        adj.MRPTYPE,
        vi.VendorItem,
        vi.PRIME_VNDR,
        vi.PURCHASING_LT,
        vi.PLANNING_LT,
        vi.ORDER_POINT_QTY,
        vi.SAFETY_STOCK
    FROM ActiveDemandJoin adj
    LEFT JOIN dbo.Prosenthal_Vendor_Items vi
        ON adj.ITEMNMBR = vi.ITEMNMBR
),
RankedData AS (
    SELECT
        ITEMNMBR,
        ItemDescription,
        UOM,
        ORDERNUMBER,
        Construct,
        DUEDATE,
        [Expiry Dates],
        [Date + Expiry],
        BEG_BAL,
        Deductions,
        Expiry,
        [PO's],
        Running_Balance,
        MRP_IssueDate,
        WCID_From_MO,
        Issued,
        Original_Required,
        Has_Issued,
        IssueDate_Mismatch,
        Early_Issue_Flag,
        CleanOrder,
        CleanItem,
        FG,
        [FG Desc],
        STSDESCR,
        MRPTYPE,
        VendorItem,
        PRIME_VNDR,
        PURCHASING_LT,
        PLANNING_LT,
        ORDER_POINT_QTY,
        SAFETY_STOCK,
        ROW_NUMBER() OVER (
            PARTITION BY ORDERNUMBER, FG, ITEMNMBR
            ORDER BY DUEDATE ASC, MRP_IssueDate ASC
        ) AS rn
    FROM VendorItemJoin
),
LedgerMatch AS (
    SELECT
        r.ITEMNMBR,
        r.ItemDescription,
        r.UOM,
        r.ORDERNUMBER,
        r.Construct,
        r.DUEDATE,
        r.[Expiry Dates],
        r.[Date + Expiry],
        r.BEG_BAL,
        r.Deductions,
        r.Expiry,
        r.[PO's],
        r.Running_Balance,
        r.MRP_IssueDate,
        r.WCID_From_MO,
        r.Issued,
        r.Original_Required,
        r.Has_Issued,
        r.IssueDate_Mismatch,
        r.Early_Issue_Flag,
        r.CleanOrder,
        r.CleanItem,
        r.FG,
        r.[FG Desc],
        r.STSDESCR,
        r.MRPTYPE,
        r.VendorItem,
        r.PRIME_VNDR,
        r.PURCHASING_LT,
        r.PLANNING_LT,
        r.ORDER_POINT_QTY,
        r.SAFETY_STOCK,
        pk.IssueDate AS Ledger_IssueDate,
        pk.QtyIssued AS Ledger_QtyIssued
    FROM RankedData r
    LEFT JOIN dbo.PK010033 pk
        ON r.CleanOrder = REPLACE(LTRIM(RTRIM(pk.ORDERNUMBER)), '-', '')
        AND r.CleanItem = REPLACE(LTRIM(RTRIM(pk.ITEMNMBR)), '-', '')
    WHERE r.rn = 1
),
FoundationLedger AS (
    SELECT
        sp.ITEMNMBR AS Spine_ITEMNMBR,
        lm.ITEMNMBR,
        lm.ItemDescription,
        lm.UOM,
        lm.ORDERNUMBER,
        lm.Construct,
        lm.DUEDATE,
        lm.[Expiry Dates],
        lm.[Date + Expiry],
        lm.BEG_BAL AS Raw_BEG_BAL,
        lm.Deductions,
        lm.Expiry,
        lm.[PO's],
        lm.Running_Balance,
        lm.MRP_IssueDate,
        lm.WCID_From_MO,
        lm.Issued,
        lm.Original_Required,
        lm.Has_Issued,
        lm.IssueDate_Mismatch,
        lm.Early_Issue_Flag,
        lm.CleanOrder,
        lm.CleanItem,
        lm.FG,
        lm.[FG Desc],
        lm.STSDESCR,
        lm.MRPTYPE,
        lm.VendorItem,
        lm.PRIME_VNDR,
        lm.PURCHASING_LT,
        lm.PLANNING_LT,
        lm.ORDER_POINT_QTY,
        lm.SAFETY_STOCK,
        lm.Ledger_IssueDate,
        lm.Ledger_QtyIssued
    FROM ItemSpine sp
    LEFT JOIN LedgerMatch lm
        ON sp.ITEMNMBR = lm.ITEMNMBR
),
FinalOutput AS (
    SELECT
        Spine_ITEMNMBR AS ITEMNMBR,
        ItemDescription,
        UOM,
        ORDERNUMBER,
        Construct,
        DUEDATE,
        [Expiry Dates],
        [Date + Expiry],
        ISNULL(Raw_BEG_BAL, 0) AS BEG_BAL,
        Deductions,
        Expiry,
        [PO's],
        Running_Balance,
        MRP_IssueDate,
        WCID_From_MO,
        Issued,
        Original_Required,
        Has_Issued,
        IssueDate_Mismatch,
        Early_Issue_Flag,
        CleanOrder,
        CleanItem,
        FG,
        [FG Desc],
        STSDESCR,
        MRPTYPE,
        VendorItem,
        PRIME_VNDR,
        PURCHASING_LT,
        PLANNING_LT,
        ORDER_POINT_QTY,
        SAFETY_STOCK,
        Ledger_IssueDate,
        Ledger_QtyIssued,
        CONCAT(
            Spine_ITEMNMBR,
            '|',
            [Date + Expiry],
            '|',
            CAST((ISNULL(Original_Required, 0) - ISNULL(Issued, 0)) AS VARCHAR(50))
        ) AS Unified_Value
    FROM FoundationLedger
)
SELECT
    ITEMNMBR,
    ItemDescription,
    UOM,
    ORDERNUMBER,
    Construct,
    DUEDATE,
    [Expiry Dates],
    [Date + Expiry],
    BEG_BAL,
    Deductions,
    Expiry,
    [PO's],
    Running_Balance,
    MRP_IssueDate,
    WCID_From_MO,
    Issued,
    Original_Required,
    Has_Issued,
    IssueDate_Mismatch,
    Early_Issue_Flag,
    CleanOrder,
    CleanItem,
    FG,
    [FG Desc],
    STSDESCR,
    MRPTYPE,
    VendorItem,
    PRIME_VNDR,
    PURCHASING_LT,
    PLANNING_LT,
    ORDER_POINT_QTY,
    SAFETY_STOCK,
    Ledger_IssueDate,
    Ledger_QtyIssued,
    Unified_Value
FROM FinalOutput;
